apiVersion: apps/v1
kind: Deployment
metadata:
  name: langchain-service
  labels:
    app: langchain-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langchain-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: langchain-service
    spec:
      containers:
      - name: langchain-service
        image: registry.digitalocean.com/helpchain/langchain-service
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
        imagePullPolicy: Always
        imagePullSecrets: registry-helpchain
---
apiVersion: v1
kind: Service
metadata:
  name: langchain-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: langchain-service